name: fec
channels:
  - conda-forge
dependencies:
  - python
  - pytest
  - scipy
  - pyyaml
  - mendeleev
  - lammps =2024.06.27=*_openmpi_*
  - openmpi =4.1.6
  - numpy
  - mpi4py
  - pylammpsmpi
  - matplotlib
  - tqdm
  - uncertainties
  - pydantic >=2.3.0
  - pyscal3
  - pyiron_workflow
  - jobflow
  - mp-api
  - pymatgen
  - calphy
  - jupyterlab
  - pyiron_atomistics
  - pyiron-data
